### ISSUE TITLE
Setup instructions for developers

### ISSUE THREAD

**Issue by derhasi** [mimez/samychan#1]
I wanted to check out your project and try to hack around it a little bit. But I'm struggling with setting up the project. After running `composer install` I end up with a site without styles. For local dev I currently use MAMP Pro.

Maybe you can post your set up steps, so I can check if I missed something.

**Comment by mimez** [comment]
hey! i just tested the setup. for me the following steps work fine:

`git clone https://github.com/mimez/samychan.git`
`cd samychan`
`composer install`
`php app/console doctrine:schema:create`
